services:
  - type: web
    name: katana-sushi-api
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build && npm run prisma:generate && npx prisma db push
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        value: change-me-in-render
      - key: DATABASE_URL
        value: postgresql://postgres:YOUR_PASSWORD@db.YOUR_PROJECT_REF.supabase.co:5432/postgres
