services:
  - type: web
    name: katana-sushi-api
    env: node
    plan: free
    region: oregon
    buildCommand: npm --prefix backend install --include=dev && npm --prefix backend run build
    preDeployCommand: cd backend && npm run prisma:push && npm run prisma:seed:prod
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
