services:
  - type: web
    name: katana-sushi-api
    env: node
    rootDir: backend
    plan: free
    region: oregon
    buildCommand: npm install --include=dev && npm run build && npm run prisma:generate
    preDeployCommand: npm run prisma:push && npm run prisma:seed:prod
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        value: change-me-in-render
      - key: DATABASE_URL
        value: "<SET_IN_DASHBOARD>"
      - key: DIRECT_URL
        value: "<SET_IN_DASHBOARD>"
