services:
  - type: web
    name: katana-sushi-api
    env: node
    rootDir: backend
    plan: free
    region: oregon
    buildCommand: npm install --include=dev && npm run prisma:generate && npm run build
    preDeployCommand: npm run prisma:push && npm run prisma:seed:prod
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
